name: Examples

on: [push]

jobs:
  benchmark:
    name: Run benchmarks
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build clang libarmadillo-dev libomp-dev libopenblas-dev

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1.12
      with:
        cmake-version: '3.20.x'

    - name: Configure CMake
      run: |
        cmake -S . -B build-release -G Ninja \
        -DCMAKE_BUILD_TYPE=Release \
        -DBUILD_TESTING=NO \
        -DBUILD_BENCHMARK=NO \
        -DBUILD_EXAMPLES=YES \
        -DCMAKE_C_COMPILER=clang \
        -DCMAKE_CXX_COMPILER=clang++ \
        -DCMAKE_CXX_FLAGS="-Wall -Wextra -Werror -Wpedantic" \
        -DCMAKE_CXX_FLAGS_RELEASE="-O2 -stdlib=libstdc++"

    - name: Build
      run: cmake --build build-release --verbose --config Release

    - name: Run examples
      run: find ./build-release/examples/ -maxdepth 1 -type f -executable -exec {} \;
